version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-security:
        applies-to: security-updates
        patterns: ["*"]
      all-dependencies:
        patterns: ["*"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-security:
        applies-to: security-updates
        patterns: ["*"]
      all-actions:
        patterns: ["*"]
