version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns: ["*"]
    runs-on: "ubuntu-latest"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-actions:
        patterns: ["*"]
    runs-on: "ubuntu-latest"
