name: Copilot Reviewer
on:
  pull_request:
    types: [opened, reopened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  request:
    uses: CloudIngenium/.github/.github/workflows/request-copilot-review.yml@main
    secrets: inherit
